#!/bin/bash

LANGUAGES='ar ca da el en_GB fr hu id ko ms nb oc pl ru si sr tr uk vi'

cd source
make gettext
sphinx-intl update -p _build/locale $(for i in $LANGUAGES; do printf -- '-l %s ' $i; done)
sphinx-intl build
for i in $LANGUAGES
do
    make -e SPHINXOPTS="-D language='"$i"'" html
    mkdir -p ../translated/$i
    cp -a _build/html ../translated/$i
done

