#!/bin/bash

LANGUAGES='it es de nl pt_BR cs sv'

cd source
make gettext
sphinx-intl update -p _build/locale $(for i in $LANGUAGES; do printf -- '-l %s ' $i; done)
sphinx-intl build
for i in $LANGUAGES
do
    make -e SPHINXOPTS="-D language='"$i"'" html
    mkdir -p ../translated/$i
    cp -a _build/html ../translated/$i
done
